version: "2"

services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=hoge
      - MYSQL_USER=hoge
      - MYSQL_PASSWORD=hoge
      - MYSQL_DATABASE=hoge
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql

  apache:
    build: .
    container_name: django-apache2
    ports:
      - '80:80'
      - '8080:8080'
    volumes: 
      - ./www:/var/www/html
