version: "2"

services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=famtory
      - MYSQL_USER=famtory
      - MYSQL_PASSWORD=famtory
      - MYSQL_DATABASE=famtory
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql

  apache:
    build: .
    container_name: django-apache2
    ports:
      - '8080:80'
      - '3500:3500'
      - '8081:8080'
    volumes: 
      - ./www:/var/www/html
